import assert from "assert";
import { partTwo } from "./day-1-trebuchet";

assert.equal(partTwo(["hmfvpctmmg6"]), 66, `hmfvpctmmg6 -> a:[${partTwo(["hmfvpctmmg6"])}] e:[66] `)
assert.equal(partTwo(["192oneightggr"]), 18, `192oneightggr -> a:[${partTwo(["192oneightggr"])}] e:[18] `)
assert.equal(partTwo(["18dxpqfcz"]), 18, `18dxpqfcz -> a:[${partTwo(["18dxpqfcz"])}] e:[18] `)
assert.equal(partTwo(["xccgpvhhseven5qflqfourkhsxqdhrbscdmbj"]), 74, `xccgpvhhseven5qflqfourkhsxqdhrbscdmbj -> a:[${partTwo(["xccgpvhhseven5qflqfourkhsxqdhrbscdmbj"])}] e:[74] `)
assert.equal(partTwo(["4jdceightseven46"]), 46, `4jdceightseven46 -> a:[${partTwo(["4jdceightseven46"])}] e:[46] `)
assert.equal(partTwo(["ninedjtjsix7"]), 97, `ninedjtjsix7 -> a:[${partTwo(["ninedjtjsix7"])}] e:[97] `)
assert.equal(partTwo(["eighttqcmmkgvhc67"]), 87)
assert.equal(partTwo(["kt82"]), 82)
assert.equal(partTwo(["dfnjmgjsmggrvljm8two4"]), 84)
assert.equal(partTwo(["2gfsveight"]), 28)
assert.equal(partTwo(["nrtwosixninefour55"]), 25)
assert.equal(partTwo(["3threesix3six89"]), 39)
assert.equal(partTwo(["twoseven5hzqsgdvmphnlppt1kjxcvpfsoneone"]), 21)
assert.equal(partTwo(["4fivethreeone18five6"]), 46)
assert.equal(partTwo(["l8pone5jtfgxffgfrone7"]), 87)
assert.equal(partTwo(["5zmjgtp2pfshdlonetdflhrz7"]), 57)
assert.equal(partTwo(["5twonepp"]), 51)
assert.equal(partTwo(["eight46pmncqjdnkbz"]), 86)
assert.equal(partTwo(["7ngmcqsevengzeightvthllqpxbfjgkc5"]), 75)
assert.equal(partTwo(["lvscttxkct7eightsdkxgffxfhhpdppbgtzbf9fiveone"]), 71)
assert.equal(partTwo(["352threedzpjvtq7onetwonefg"]), 31)
assert.equal(partTwo(["31eight"]), 38)

assert.equal(partTwo(["6zbhrsnzsixxmjvsnfsixnine"]), 69)
assert.equal(partTwo(["tbgdjscgtkn8pdtld"]), 88)
assert.equal(partTwo(["643nbsntbjmbninezfbnkggfivefour"]), 64)
assert.equal(partTwo(["vxnsvnine5seventhree2mksgsjbpkqdgbs"]), 92)
assert.equal(partTwo(["2xchcfiveeightrnldvblbfqnmvmn"]), 28)
assert.equal(partTwo(["5kbpnbtpnzbeight9"]), 59)
assert.equal(partTwo(["three2eightseven"]), 37)
assert.equal(partTwo(["sszgqcvtmlcmd95six1jmsnfmfmlktdvtskrp"]), 91)
assert.equal(partTwo(["xlmthreemdrvgzfnseven3"]), 33)
assert.equal(partTwo(["ntwoncnpdjg8"]), 28)
assert.equal(partTwo(["sevenfivethree968"]), 78)
assert.equal(partTwo(["four6twooneonejmxgtzz6three"]), 43)
assert.equal(partTwo(["893jfmmnk6lmhqmtxgkmtxq8"]), 88)
assert.equal(partTwo(["pvconeight3dmprrnmj2cpqmgmvkqtqcn71"]), 11)
assert.equal(partTwo(["five688seven"]), 57)
assert.equal(partTwo(["67six"]), 66)
assert.equal(partTwo(["54xcthreenlhthreeone7"]), 57)
assert.equal(partTwo(["6bkt4hlhg7"]), 67)
assert.equal(partTwo(["kvxpgcnqkhkhxthreerxkxt9cgcnvcvkxdddsdfjrqmn"]), 39)
assert.equal(partTwo(["4sixseventstk3"]), 43)
assert.equal(partTwo(["qmoneightnine583crcfeight4eight"]), 18)
assert.equal(partTwo(["7sevendxpckzsm885"]), 75)
assert.equal(partTwo(["seven7threesllgfvccbglbscdg"]), 73)
assert.equal(partTwo(["ninefbnnpvxcmjpjrts3eightzsqmxxkkgg6"]), 96)
assert.equal(partTwo(["nxhmxngoneqqqxlbqfcr5pkpthcdxtx"]), 15)
assert.equal(partTwo(["threeseven5twocdzkpp"]), 32)

assert.equal(partTwo(["35sixgtqzsnjh6three"]), 33)
assert.equal(partTwo(["sixrbrdblgj2prpsgnl9686"]), 66)
assert.equal(partTwo(["2seven2"]), 22)
assert.equal(partTwo(["cdh3"]), 33)
assert.equal(partTwo(["sixtsfive8pdfivetwonegg"]), 61)
assert.equal(partTwo(["ccsbzxsevenoneeight76"]), 76)
assert.equal(partTwo(["jbfkngpjlvbtwofiveone1pdphmps"]), 21)
assert.equal(partTwo(["beightdcrtnchtnine6fourthree"]), 83)
assert.equal(partTwo(["sixsxzonenvvkljfthreezhp37"]), 67)
assert.equal(partTwo(["seventwovd17"]), 77)

assert.equal(partTwo(["hmfs69one2xeightfive"]), 65)
assert.equal(partTwo(["3sbhjfkjtnlrzqrcrbkbcxzcmsm69nine"]), 39)
assert.equal(partTwo(["njdkcdprjgpn9fs"]), 99)
assert.equal(partTwo(["bg56ts"]), 56)
assert.equal(partTwo(["one542onetwo"]), 12)
assert.equal(partTwo(["ninernsbhqzqc6one4sixgsdcfsix"]), 96)
assert.equal(partTwo(["2onethree24onetwo"]), 22)
assert.equal(partTwo(["8sixmclpsdvvgs6eight7lnzhsgzjxdsn"]), 87)
assert.equal(partTwo(["one5onefour"]), 14)
assert.equal(partTwo(["c1fournine"]), 19)

assert.equal(partTwo(["nbqbgxdtwo8fourxrgszvbxqtwo2"]), 22)
assert.equal(partTwo(["9nineffsevennine3seven3fnvsxmvrk"]), 93)
assert.equal(partTwo(["tsp5"]), 55)
assert.equal(partTwo(["oneseven9threesixgjnkv"]), 16)
assert.equal(partTwo(["fourtwo4two3hfnpzhvcx5"]), 45)
assert.equal(partTwo(["15eightsthhfgsjtqcbxvxqj"]), 18)
assert.equal(partTwo(["jdvssqjd9scqnlsfive2two"]), 92)
assert.equal(partTwo(["three9sevenzdgpjqkzh7four"]), 34)
assert.equal(partTwo(["8th632onezhfcv8"]), 88)
assert.equal(partTwo(["7sixlcxnhdmphbbbpsxrb1oneprx"]), 71)
assert.equal(partTwo(["four4eightnine"]), 49)
assert.equal(partTwo(["gxbsix7pqkseven"]), 67)

assert.equal(partTwo(["4teightx3five6eight"]), 48)
assert.equal(partTwo(["sevenzrzm72mrgcxld"]), 72)
assert.equal(partTwo(["7foureightthreesixqcddc7smksqzxhqs"]), 77)
assert.equal(partTwo(["hpcpqbhsfivesixninembvbpqphhmrtthree9"]), 59)
assert.equal(partTwo(["ninexzgctccxbgjxvtngxfvkthree8"]), 98)
assert.equal(partTwo(["fdmvqcktrjh8fiveglzhchx55khhntcbndddtjccsx"]), 85)
assert.equal(partTwo(["8fivenine"]), 89)
assert.equal(partTwo(["mxsbjjcbpceight18"]), 88)
assert.equal(partTwo(["vjvddlttpsgbvf99"]), 99)
assert.equal(partTwo(["5five3"]), 53)